//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonDataExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonDataExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in processing Query, Please check Query Format : {0}.
        /// </summary>
        internal static string STR_ERROR_PROCESSING_QUERY {
            get {
                return ResourceManager.GetString("STR_ERROR_PROCESSING_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found, modify the query.
        /// </summary>
        internal static string STR_INFO_MODIFY_QUERY {
            get {
                return ResourceManager.GetString("STR_INFO_MODIFY_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying {0} / {1} Items.
        /// </summary>
        internal static string STR_INFO_QUERY_RESULTS {
            get {
                return ResourceManager.GetString("STR_INFO_QUERY_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying {0} Items.
        /// </summary>
        internal static string STR_INFO_QUERY_RESULTS_LIST {
            get {
                return ResourceManager.GetString("STR_INFO_QUERY_RESULTS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string STR_TITLE_ERROR {
            get {
                return ResourceManager.GetString("STR_TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string STR_TITLE_WARNING {
            get {
                return ResourceManager.GetString("STR_TITLE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file can&apos;t be empty.
        /// </summary>
        internal static string STR_VAL_INPUT_FILE_EMPTY {
            get {
                return ResourceManager.GetString("STR_VAL_INPUT_FILE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input file format.
        /// </summary>
        internal static string STR_VAL_INPUT_FILE_FORMAT {
            get {
                return ResourceManager.GetString("STR_VAL_INPUT_FILE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find input file.
        /// </summary>
        internal static string STR_VAL_INPUT_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("STR_VAL_INPUT_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query cannot be empty.
        /// </summary>
        internal static string STR_VAL_QUERY_EMPTY {
            get {
                return ResourceManager.GetString("STR_VAL_QUERY_EMPTY", resourceCulture);
            }
        }
    }
}
